# Generated by Django 5.1.4 on 2025-02-03 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('tenderee', models.CharField(max_length=200, verbose_name='招标单位')),
                ('bidder', models.CharField(max_length=200, verbose_name='投标单位')),
                ('project_type', models.CharField(choices=[('WELFARE', '企业福利'), ('FSD', '食材配送'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='项目类型')),
                ('bid_deadline', models.DateTimeField(verbose_name='投标截止时间')),
                ('current_stage', models.CharField(choices=[('DRAFT', '草稿'), ('ANALYZING', '分析中'), ('PENDING_CONFIRM', '待确认'), ('WRITING', '编写中'), ('REVIEWING', '审核中'), ('REVISING', '修订中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='当前阶段')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='是否紧急')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('DRAFT', '草稿'), ('ANALYZING', '分析中'), ('PENDING_CONFIRM', '待确认'), ('WRITING', '编写中'), ('REVIEWING', '审核中'), ('REVISING', '修订中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], max_length=20, verbose_name='原阶段')),
                ('to_stage', models.CharField(choices=[('DRAFT', '草稿'), ('ANALYZING', '分析中'), ('PENDING_CONFIRM', '待确认'), ('WRITING', '编写中'), ('REVIEWING', '审核中'), ('REVISING', '修订中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], max_length=20, verbose_name='新阶段')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_histories', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目阶段历史',
                'verbose_name_plural': '项目阶段历史',
                'ordering': ['-operation_time'],
            },
        ),
    ]
