# Generated by Django 5.1.4 on 2025-02-28 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('tenderee', models.CharField(max_length=200, verbose_name='招标单位')),
                ('bidder', models.CharField(blank=True, default='', max_length=200, verbose_name='投标单位')),
                ('project_type', models.CharField(choices=[('WELFARE', '企业福利'), ('FSD', '食材配送'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='项目类型')),
                ('bid_deadline', models.DateTimeField(blank=True, null=True, verbose_name='投标截止时间')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='IN_PROGRESS', max_length=20, verbose_name='项目状态')),
                ('current_stage', models.CharField(choices=[('INITIALIZATION', '项目初始化'), ('TENDER_ANALYSIS', '招标文件解读'), ('BID_WRITING', '投标文件撰写'), ('BID_REVISION', '投标文件修订'), ('BID_PRODUCTION', '生产投标文件')], default='INITIALIZATION', max_length=20, verbose_name='当前阶段')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='是否紧急')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(choices=[('INITIALIZATION', '项目初始化'), ('TENDER_ANALYSIS', '招标文件解读'), ('BID_WRITING', '投标文件撰写'), ('BID_REVISION', '投标文件修订'), ('BID_PRODUCTION', '生产投标文件')], max_length=20, verbose_name='原阶段')),
                ('to_stage', models.CharField(choices=[('INITIALIZATION', '项目初始化'), ('TENDER_ANALYSIS', '招标文件解读'), ('BID_WRITING', '投标文件撰写'), ('BID_REVISION', '投标文件修订'), ('BID_PRODUCTION', '生产投标文件')], max_length=20, verbose_name='新阶段')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_histories', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目阶段历史',
                'verbose_name_plural': '项目阶段历史',
                'ordering': ['-operation_time'],
            },
        ),
    ]
