# Generated by Django 5.1.4 on 2025-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetask',
            name='type',
            field=models.CharField(choices=[('UPLOAD_TENDER_FILE', '上传招标文件'), ('DOCX_EXTRACTION_TASK', '提取文档信息'), ('DOCX_TREE_BUILD_TASK', '构建文档树'), ('OTHER', '其他')], default='OTHER', max_length=50, verbose_name='任务类型'),
        ),
    ]
