# Generated by Django 5.1.4 on 2025-03-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='to_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], max_length=20, null=True),
        ),
    ]
