# Generated by Django 5.1.4 on 2025-03-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstage',
            name='remarks',
        ),
    ]
