# Generated by Django 5.1.4 on 2025-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bid_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投标截止时间'),
        ),
    ]
