# Generated by Django 5.1.4 on 2025-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docxextractiontask',
            name='extracted_elements',
        ),
        migrations.RemoveField(
            model_name='docxextractiontask',
            name='improved_docx_elements',
        ),
        migrations.RemoveField(
            model_name='docxextractiontask',
            name='outline_analysis_result',
        ),
        migrations.AddField(
            model_name='docxextractiontask',
            name='tiptap_content',
            field=models.JSONField(blank=True, help_text='存储tiptap内容', null=True, verbose_name='tiptap内容'),
        ),
    ]
