# Generated by Django 5.1.4 on 2025-04-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="prompt",
        ),
        migrations.RemoveField(
            model_name="task",
            name="related_company_info",
        ),
        migrations.AddField(
            model_name="projectstage",
            name="tender_file_extration",
            field=models.JSONField(
                blank=True,
                help_text="存储招标文件提取的内容",
                null=True,
                verbose_name="招标文件提取的内容",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="context_description",
            field=models.TextField(blank=True, verbose_name="上下文描述"),
        ),
        migrations.AddField(
            model_name="task",
            name="instruction",
            field=models.JSONField(
                blank=True, help_text="存储指令", null=True, verbose_name="指令"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="instruction_description",
            field=models.TextField(blank=True, verbose_name="指令描述"),
        ),
        migrations.AddField(
            model_name="task",
            name="supplement",
            field=models.JSONField(
                blank=True, help_text="存储补充信息", null=True, verbose_name="补充信息"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="supplement_description",
            field=models.TextField(blank=True, verbose_name="补充描述"),
        ),
    ]
