# Generated by Django 5.1.4 on 2025-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_urgent',
        ),
        migrations.AddField(
            model_name='project',
            name='starred',
            field=models.BooleanField(default=False, verbose_name='是否标星'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', '未开始'), ('ACTIVE', '激活中'), ('COMPLETED', '完成'), ('FAILED', '失败')], default='NOT_STARTED', max_length=20, verbose_name='状态'),
        ),
    ]
