# Generated by Django 5.1.4 on 2025-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetask',
            name='progress',
        ),
        migrations.AlterField(
            model_name='project',
            name='current_active_stage',
            field=models.CharField(choices=[('TENDER_ANALYSIS', '招标文件分析'), ('BID_WRITING', '投标文件编写')], default='TENDER_ANALYSIS', max_length=20, verbose_name='当前活动阶段'),
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='from_stage',
            field=models.CharField(choices=[('TENDER_ANALYSIS', '招标文件分析'), ('BID_WRITING', '投标文件编写')], max_length=20, verbose_name='原阶段'),
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='to_stage',
            field=models.CharField(choices=[('TENDER_ANALYSIS', '招标文件分析'), ('BID_WRITING', '投标文件编写')], max_length=20, verbose_name='新阶段'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_type',
            field=models.CharField(choices=[('TENDER_ANALYSIS', '招标文件分析'), ('BID_WRITING', '投标文件编写')], max_length=20, verbose_name='阶段类型'),
        ),
    ]
