# Generated by Django 5.1.4 on 2025-03-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecthistory_from_status_projecthistory_to_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_code',
        ),
    ]
