# Generated by Django 5.1.4 on 2025-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_is_urgent_project_starred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_confirmed',
            field=models.BooleanField(default=False, verbose_name='用户确认'),
        ),
    ]
