# Generated by Django 5.1.4 on 2025-03-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_docxextractiontask_extracted_elements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocxTreeBuildTask',
        ),
    ]
