# Generated by Django 5.1.4 on 2025-06-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_tender_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tender_file_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
