# Generated by Django 5.1.4 on 2025-04-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_remove_task_prompt_remove_task_related_company_info_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectstage",
            old_name="tender_file_extration",
            new_name="tender_file_extraction",
        ),
    ]
