# Generated by Django 5.1.4 on 2025-06-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_tender_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="bid_deadline",
        ),
        migrations.RemoveField(
            model_name="project",
            name="current_active_stage",
        ),
        migrations.RemoveField(
            model_name="project",
            name="index_path_map_L1",
        ),
        migrations.RemoveField(
            model_name="project",
            name="index_path_map_L2",
        ),
        migrations.RemoveField(
            model_name="project",
            name="index_path_map_L3",
        ),
        migrations.RemoveField(
            model_name="project",
            name="outline_L1",
        ),
        migrations.RemoveField(
            model_name="project",
            name="outline_L2",
        ),
        migrations.RemoveField(
            model_name="project",
            name="outline_L3",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tender_file_extraction",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tender_file_extraction_L1",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tender_file_extraction_L2",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tender_file_extraction_L3",
        ),
    ]
