# Generated by Django 5.1.4 on 2025-03-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_basetask_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderFileUploadTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.basetask')),
            ],
            bases=('projects.basetask',),
        ),
    ]
