# Generated by Django 5.1.4 on 2025-03-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_basetask_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocxExtractionTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.basetask')),
                ('extracted_elements', models.JSONField(blank=True, help_text='存储从文档中提取的结构化元素', null=True, verbose_name='提取的文档元素')),
                ('outline_analysis_result', models.JSONField(blank=True, help_text='存储大纲分析的结果', null=True, verbose_name='大纲分析结果')),
                ('improved_docx_elements', models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='初步大纲优化后的文档元素')),
            ],
            bases=('projects.basetask',),
        ),
        migrations.CreateModel(
            name='DocxTreeBuildTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.basetask')),
                ('docxtree', models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='初步大纲优化后的文档元素')),
                ('more_subtitles', models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='更多子标题')),
            ],
            options={
                'verbose_name': '文档树构建任务',
                'verbose_name_plural': '文档树构建任务',
            },
            bases=('projects.basetask',),
        ),
        migrations.RemoveField(
            model_name='documenttreebuildingtask',
            name='basetask_ptr',
        ),
        migrations.DeleteModel(
            name='DocumentExtractionTask',
        ),
        migrations.DeleteModel(
            name='DocumentTreeBuildingTask',
        ),
    ]
