# Generated by Django 5.1.4 on 2025-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_rename_tender_file_extration_projectstage_tender_file_extraction",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectstage",
            name="tender_file_extraction",
        ),
        migrations.AddField(
            model_name="project",
            name="tender_file_extraction",
            field=models.JSONField(
                blank=True,
                help_text="存储招标文件提取的内容",
                null=True,
                verbose_name="招标文件提取的内容",
            ),
        ),
    ]
