# Generated by Django 5.1.4 on 2025-06-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_tender_file_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tender_file_meta",
        ),
    ]
