# Generated by Django 5.1.4 on 2025-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tenderfileuploadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetask',
            name='lock_status',
            field=models.CharField(choices=[('LOCKED', '锁定'), ('UNLOCKED', '解锁')], default='UNLOCKED', max_length=20, verbose_name='锁定状态'),
        ),
    ]
