# Generated by Django 5.1.4 on 2025-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_project_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectstage',
            name='projects_pr_project_263515_idx',
        ),
        migrations.RenameField(
            model_name='projectstage',
            old_name='status',
            new_name='stage_status',
        ),
        migrations.RenameField(
            model_name='projectstage',
            old_name='stage',
            new_name='stage_type',
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('project', 'stage_type')},
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'stage_type'], name='projects_pr_project_4db5a0_idx'),
        ),
    ]
