# Generated by Django 5.1.4 on 2025-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_user_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_confirmed',
        ),
        migrations.AddField(
            model_name='task',
            name='lockedEditor',
            field=models.BooleanField(default=False, verbose_name='可编辑状态'),
        ),
    ]
