# Generated by Django 5.1.4 on 2025-03-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectstage_projects_pr_project_263515_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_histories', to='projects.project', verbose_name='项目'),
        ),
    ]
