# Generated by Django 5.1.4 on 2025-03-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_task_user_confirmed_task_lockededitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lockedEditor',
        ),
    ]
