# Generated by Django 5.1.4 on 2025-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_tender_file_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="mime_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="文件类型"
            ),
        ),
    ]
