# Generated by Django 5.1.4 on 2025-06-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_mime_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="mime_type",
        ),
    ]
