# Generated by Django 5.1.4 on 2025-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_task_lockededitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tiptap_content',
            new_name='docx_tiptap',
        ),
        migrations.AddField(
            model_name='task',
            name='context',
            field=models.JSONField(blank=True, help_text='存储上下文', null=True, verbose_name='上下文'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_Tiptapjson',
            field=models.JSONField(blank=True, help_text='存储结果JSON', null=True, verbose_name='结果JSON'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_html',
            field=models.TextField(blank=True, help_text='存储结果HTML', null=True, verbose_name='结果HTML'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_markdown',
            field=models.TextField(blank=True, help_text='存储结果Markdown', null=True, verbose_name='结果Markdown'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_raw',
            field=models.JSONField(blank=True, help_text='存储结果原始数据', null=True, verbose_name='结果原始数据'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('UPLOAD_TENDER_FILE', '上传招标文件'), ('DOCX_EXTRACTION_TASK', '提取文档信息'), ('OUTLINE_ANALYSIS_TASK', '分析文档结构'), ('OTHER', '其他')], default='OTHER', max_length=50, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='taskchangehistory',
            name='task_type',
            field=models.CharField(choices=[('UPLOAD_TENDER_FILE', '上传招标文件'), ('DOCX_EXTRACTION_TASK', '提取文档信息'), ('OUTLINE_ANALYSIS_TASK', '分析文档结构'), ('OTHER', '其他')], default='OTHER', max_length=50, verbose_name='任务类型'),
        ),
    ]
