# Generated by Django 5.1.4 on 2025-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_task_context_tokens_task_final_result_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="outline_L1",
            field=models.JSONField(
                blank=True, help_text="存储大纲L1", null=True, verbose_name="大纲L1"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="outline_L2",
            field=models.JSONField(
                blank=True, help_text="存储大纲L2", null=True, verbose_name="大纲L2"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="outline_L3",
            field=models.JSONField(
                blank=True, help_text="存储大纲L3", null=True, verbose_name="大纲L3"
            ),
        ),
    ]
