# Generated by Django 5.1.4 on 2025-03-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_tiptap_content_task_docx_tiptap_task_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='index_path_map',
            field=models.JSONField(blank=True, help_text='存储索引路径映射', null=True, verbose_name='索引路径映射'),
        ),
    ]
