# Generated by Django 5.1.4 on 2025-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_index_path_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='context',
        ),
        migrations.AddField(
            model_name='task',
            name='additional_input',
            field=models.JSONField(blank=True, help_text='存储补充输入', null=True, verbose_name='补充输入'),
        ),
        migrations.AddField(
            model_name='task',
            name='data_input',
            field=models.JSONField(blank=True, help_text='存储数据输入', null=True, verbose_name='数据输入'),
        ),
        migrations.AddField(
            model_name='task',
            name='llm_config',
            field=models.JSONField(blank=True, help_text='存储模型配置', null=True, verbose_name='模型配置'),
        ),
        migrations.AddField(
            model_name='task',
            name='output_format',
            field=models.JSONField(blank=True, help_text='存储输出格式', null=True, verbose_name='输出格式'),
        ),
        migrations.AddField(
            model_name='task',
            name='prompt_template',
            field=models.JSONField(blank=True, help_text='存储prompt模板', null=True, verbose_name='prompt模板'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_Tiptapjson',
            field=models.JSONField(blank=True, help_text='存储结果Tiptap JSON', null=True, verbose_name='结果Tiptap JSON'),
        ),
    ]
