# Generated by Django 5.1.4 on 2025-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0007_project_index_path_map_l1_project_index_path_map_l2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tender_file_extraction_L1",
            field=models.JSONField(
                blank=True,
                help_text="存储招标文件更新L1",
                null=True,
                verbose_name="招标文件更新L1",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tender_file_extraction_L2",
            field=models.JSONField(
                blank=True,
                help_text="存储招标文件更新L2",
                null=True,
                verbose_name="招标文件更新L2",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tender_file_extraction_L3",
            field=models.JSONField(
                blank=True,
                help_text="存储招标文件更新L3",
                null=True,
                verbose_name="招标文件更新L3",
            ),
        ),
    ]
