# Generated by Django 5.1.4 on 2025-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_tender_file_extraction_l1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_level",
            field=models.IntegerField(default=0, verbose_name="任务层级"),
        ),
    ]
