# Generated by Django 5.1.4 on 2025-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_task_context_task_additional_input_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "未开始"),
                    ("CONFIGURING", "配置中"),
                    ("PROCESSING", "处理中"),
                    ("REVIEWING", "审核中"),
                    ("COMPLETED", "完成"),
                    ("FAILED", "失败"),
                ],
                default="NOT_STARTED",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
