# Generated by Django 5.1.4 on 2025-05-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_task_task_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuringAgentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(db_index=True, max_length=100)),
                ("document_type", models.CharField(max_length=20)),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "文档结构化内容",
                "verbose_name_plural": "文档结构化内容",
                "db_table": "structuring_agent_document",
                "indexes": [
                    models.Index(
                        fields=["project_id", "document_type"],
                        name="structuring_project_082e01_idx",
                    )
                ],
                "unique_together": {("project_id", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="StructuringAgentState",
            fields=[
                (
                    "project_id",
                    models.CharField(
                        db_index=True, max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                ("state_history", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "文档结构化状态",
                "verbose_name_plural": "文档结构化状态",
                "db_table": "structuring_agent_state",
                "indexes": [
                    models.Index(
                        fields=["project_id"], name="structuring_project_fa393d_idx"
                    )
                ],
            },
        ),
    ]
