# Generated by Django 5.1.4 on 2025-04-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="analysis_duration",
            field=models.IntegerField(
                blank=True, help_text="存储分析时长", null=True, verbose_name="分析时长"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="context",
            field=models.JSONField(
                blank=True, help_text="存储上下文", null=True, verbose_name="上下文"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="存储错误信息", null=True, verbose_name="错误信息"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="final_result",
            field=models.JSONField(
                blank=True, help_text="存储最终结果", null=True, verbose_name="最终结果"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="in_tokens",
            field=models.IntegerField(
                blank=True,
                help_text="存储输入token",
                null=True,
                verbose_name="输入token",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="out_tokens",
            field=models.IntegerField(
                blank=True,
                help_text="存储输出token",
                null=True,
                verbose_name="输出token",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="prompt",
            field=models.JSONField(
                blank=True, help_text="存储prompt", null=True, verbose_name="prompt"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_company_info",
            field=models.JSONField(
                blank=True, help_text="存储公司信息", null=True, verbose_name="公司信息"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="存储任务完成时间",
                null=True,
                verbose_name="任务完成时间",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="存储任务开始时间",
                null=True,
                verbose_name="任务开始时间",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="total_tokens",
            field=models.IntegerField(
                blank=True, help_text="存储总token", null=True, verbose_name="总token"
            ),
        ),
    ]
