# Generated by Django 5.1.4 on 2025-04-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_task_analysis_duration_task_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="projects.task"
            ),
        ),
    ]
