# Generated by Django 5.1.4 on 2025-02-06 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('size', models.BigIntegerField()),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'WORD'), ('EXCEL', 'EXCEL'), ('IMAGE', 'IMAGE'), ('OTHER', 'OTHER')], max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(choices=[('NONE', 'None'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NONE', max_length=20)),
                ('processing_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
                ('read_users', models.ManyToManyField(blank=True, related_name='readable_files', to=settings.AUTH_USER_MODEL)),
                ('write_users', models.ManyToManyField(blank=True, related_name='writable_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_records',
            },
        ),
        migrations.CreateModel(
            name='FileProjectLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('link_type', models.CharField(choices=[('ATTACHMENT', 'Attachment'), ('REFERENCE', 'Reference')], max_length=20)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='projects.project')),
                ('file_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='files.filerecord')),
            ],
            options={
                'db_table': 'file_project_links',
                'constraints': [models.UniqueConstraint(fields=('file_record', 'project', 'link_type'), name='unique_file_project_link')],
            },
        ),
    ]
