# Generated by Django 5.1.4 on 2025-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='processing_status',
            field=models.CharField(choices=[('NONE', 'None'), ('UPLOADING', 'Uploading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NONE', max_length=20),
        ),
    ]
