# Generated by Django 5.1.4 on 2025-01-31 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filerecord_file_alter_fileprojectlink_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecord',
            name='url',
        ),
    ]
