# Generated by Django 5.1.4 on 2025-01-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_filerecord_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileprojectlink',
            old_name='file',
            new_name='file_key',
        ),
    ]
