#version: '3.8'

services:
  # 数据库服务
  db:
    image: postgres:14.17
    container_name: bidpilot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - bidpilot_network

  # 后端Django服务
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: bidpilot_backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - bidpilot_network

networks:
  bidpilot_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:


