# Generated by Django 5.1.4 on 2025-03-11 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='文档标题')),
                ('status', models.CharField(choices=[('PENDING', '待分析'), ('PROCESSING', '分析中'), ('COMPLETED', '已完成'), ('FAILED', '分析失败'), ('CONFIRMED', '已确认')], db_index=True, default='PENDING', max_length=20, verbose_name='分析状态')),
                ('analysis_questions', models.JSONField(blank=True, help_text='存储需要分析的问题集合（如 ["资质要求", "技术参数"]）', null=True, verbose_name='分析问题集')),
                ('analysis_result', models.JSONField(blank=True, db_index=True, null=True, verbose_name='分析结果')),
                ('extracted_elements', models.JSONField(blank=True, help_text='存储从文档中提取的结构化元素', null=True, verbose_name='提取的文档元素')),
                ('outline_analysis_result', models.JSONField(blank=True, help_text='存储大纲分析的结果', null=True, verbose_name='大纲分析结果')),
                ('improved_docx_elements', models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='初步大纲优化后的文档元素')),
                ('docxtree', models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='初步大纲优化后的文档元素')),
                ('more_subtitles', models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='更多子标题')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('raw_xml', models.TextField(blank=True, help_text='存储从DOCX提取的原始XML内容', null=True, verbose_name='原始XML')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='处理耗时')),
                ('analysis_version', models.CharField(default='1.0.0', max_length=50, verbose_name='分析器版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_analyses', to=settings.AUTH_USER_MODEL, verbose_name='确认者')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analyses', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文档分析',
                'verbose_name_plural': '文档分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
