# Generated by Django 5.1.4 on 2025-02-11 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='文档标题')),
                ('status', models.CharField(choices=[('PENDING', '待分析'), ('PROCESSING', '分析中'), ('COMPLETED', '已完成'), ('FAILED', '分析失败'), ('CONFIRMED', '已确认')], db_index=True, default='PENDING', max_length=20, verbose_name='分析状态')),
                ('file_type', models.CharField(default='DOCX', max_length=20, verbose_name='文件类型')),
                ('file_size', models.PositiveIntegerField(null=True, verbose_name='文件大小(bytes)')),
                ('analysis_questions', models.JSONField(blank=True, help_text='存储需要分析的问题集合（如 ["资质要求", "技术参数"]）', null=True, verbose_name='分析问题集')),
                ('analysis_result', models.JSONField(blank=True, db_index=True, null=True, verbose_name='分析结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('raw_xml', models.TextField(blank=True, help_text='存储从DOCX提取的原始XML内容', null=True, verbose_name='原始XML')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='处理耗时')),
                ('analysis_version', models.CharField(default='1.0.0', max_length=50, verbose_name='分析器版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_analyses', to=settings.AUTH_USER_MODEL, verbose_name='确认者')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analyses', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('file_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='files.filerecord', verbose_name='关联文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '文档分析',
                'verbose_name_plural': '文档分析',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='doc_analysi_status_6bc99c_idx'), models.Index(fields=['project', 'status'], name='doc_analysi_project_9640ed_idx')],
                'unique_together': {('project', 'file_record', 'title')},
            },
        ),
    ]
