# Generated by Django 5.1.4 on 2025-02-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_analysis', '0001_initial'),
        ('files', '0002_alter_filerecord_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentanalysis',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='documentanalysis',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='file_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='files.filerecord', verbose_name='关联文件'),
        ),
    ]
