# Generated by Django 5.1.4 on 2025-03-11 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc_analysis', '0001_initial'),
        ('files', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='file_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='files.filerecord', verbose_name='关联文件'),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='documentanalysis',
            index=models.Index(fields=['status', 'created_at'], name='doc_analysi_status_6bc99c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentanalysis',
            index=models.Index(fields=['project', 'status'], name='doc_analysi_project_9640ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentanalysis',
            unique_together={('project', 'file_record', 'title')},
        ),
    ]
