# Generated by Django 5.1.4 on 2025-03-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc_analysis', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='file_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='files.filerecord', verbose_name='关联文件'),
        ),
    ]
