# Generated by Django 5.1.4 on 2025-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_analysis', '0002_remove_documentanalysis_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='extracted_elements',
            field=models.JSONField(blank=True, help_text='存储从文档中提取的结构化元素', null=True, verbose_name='提取的文档元素'),
        ),
    ]
