# Generated by Django 5.1.4 on 2025-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_analysis', '0006_documentanalysis_docxtree'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='more_subtitles',
            field=models.JSONField(blank=True, help_text='存储从经过初步大纲优化的结构化元素', null=True, verbose_name='更多子标题'),
        ),
    ]
