# Generated by Django 5.1.4 on 2025-05-30 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0010_structuringagentdocument_structuringagentstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuringAgentStorage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_state_history",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Agent状态历史"
                    ),
                ),
                (
                    "agent_message_history",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Agent消息历史"
                    ),
                ),
                (
                    "raw_document",
                    models.JSONField(blank=True, null=True, verbose_name="原始文档"),
                ),
                (
                    "h1_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="一级大纲文档"
                    ),
                ),
                (
                    "h2h3_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="更细大纲文档"
                    ),
                ),
                (
                    "intro_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="含前言目录的文档"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structuring_agent_storage",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "结构化Agent存储",
                "verbose_name_plural": "结构化Agent存储",
                "db_table": "structuring_agent_storage",
            },
        ),
    ]
