# Generated by Django 5.1.4 on 2025-06-20 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAgentStorage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_state_history",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Agent状态历史"
                    ),
                ),
                (
                    "agent_message_history",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Agent消息历史"
                    ),
                ),
                (
                    "raw_document",
                    models.JSONField(blank=True, null=True, verbose_name="原始文档"),
                ),
                (
                    "h1_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="一级大纲文档"
                    ),
                ),
                (
                    "h2h3_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="更细大纲文档"
                    ),
                ),
                (
                    "intro_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="含前言目录的文档"
                    ),
                ),
                (
                    "final_document",
                    models.JSONField(blank=True, null=True, verbose_name="最终文档"),
                ),
                (
                    "review_suggestions",
                    models.JSONField(
                        blank=True, null=True, verbose_name="招标文档结构修正建议文档"
                    ),
                ),
                (
                    "chapters_md",
                    models.JSONField(blank=True, null=True, verbose_name="章节md"),
                ),
                (
                    "topic_chapters_map",
                    models.JSONField(
                        blank=True, null=True, verbose_name="章节内容主题对应表"
                    ),
                ),
                (
                    "raw_topic_todos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="章节内容主题对应表"
                    ),
                ),
                (
                    "integrated_topic_todos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="合并同类项后的_todos"
                    ),
                ),
                (
                    "draft_bid_document",
                    models.JSONField(
                        blank=True, null=True, verbose_name="草稿投标文件"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_agent_storage",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_agent_storage",
            },
        ),
    ]
