# Generated by Django 5.1.4 on 2025-06-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal_server", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE structuring_agent_storage RENAME TO project_agent_storage;",
            reverse_sql="ALTER TABLE project_agent_storage RENAME TO structuring_agent_storage;",
        ),
    ]
