# Generated by Django 5.1.4 on 2025-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuringagentstorage",
            name="final_document",
            field=models.JSONField(blank=True, null=True, verbose_name="最终文档"),
        ),
    ]
