# Generated by Django 5.1.4 on 2025-06-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_server", "0002_structuringagentstorage_final_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuringagentstorage",
            name="chapters_md",
            field=models.JSONField(blank=True, null=True, verbose_name="章节md"),
        ),
    ]
