# Generated by Django 5.1.4 on 2025-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_server", "0003_structuringagentstorage_chapters_md"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuringagentstorage",
            name="review_suggestions",
            field=models.JSONField(
                blank=True, null=True, verbose_name="招标文档结构修正建议文档"
            ),
        ),
    ]
