# Generated by Django 5.1.4 on 2025-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_server", "0004_structuringagentstorage_review_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuringagentstorage",
            name="draft_bid_document",
            field=models.JSONField(blank=True, null=True, verbose_name="草稿投标文件"),
        ),
        migrations.AddField(
            model_name="structuringagentstorage",
            name="integrated_topic_todos",
            field=models.JSONField(
                blank=True, null=True, verbose_name="合并同类项后的_todos"
            ),
        ),
        migrations.AddField(
            model_name="structuringagentstorage",
            name="raw_topic_todos",
            field=models.JSONField(
                blank=True, null=True, verbose_name="章节内容主题对应表"
            ),
        ),
        migrations.AddField(
            model_name="structuringagentstorage",
            name="topic_chapters_map",
            field=models.JSONField(
                blank=True, null=True, verbose_name="章节内容主题对应表"
            ),
        ),
    ]
