# Generated by Django 5.1.4 on 2025-05-13 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="计划名称")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "基础版"),
                            ("pro", "专业版"),
                            ("enterprise", "企业版"),
                        ],
                        max_length=20,
                        verbose_name="计划类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="月价格"
                    ),
                ),
                (
                    "project_limit",
                    models.PositiveIntegerField(verbose_name="项目数量限制"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "订阅计划",
                "verbose_name_plural": "订阅计划",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始日期"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="结束日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "生效中"),
                            ("expired", "已过期"),
                            ("canceled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remaining_projects",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="剩余可用项目数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscription.subscriptionplan",
                        verbose_name="订阅计划",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户订阅",
                "verbose_name_plural": "用户订阅",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("subscribe", "新订阅"),
                            ("renew", "续订"),
                            ("upgrade", "升级"),
                            ("cancel", "取消"),
                            ("expire", "过期"),
                            ("project_used", "项目使用"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="subscription.usersubscription",
                        verbose_name="订阅",
                    ),
                ),
            ],
            options={
                "verbose_name": "订阅日志",
                "verbose_name_plural": "订阅日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("mock", "模拟支付"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("success", "支付成功"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="交易ID"
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "raw_response",
                    models.JSONField(blank=True, null=True, verbose_name="原始响应"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscription.usersubscription",
                        verbose_name="关联订阅",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
