/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsImport } from './routes/projects'
import { Route as ProjectsIdImport } from './routes/projects.$id'
import { Route as AuthServiceTermImport } from './routes/auth/service-term'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthPrivacyPolicyImport } from './routes/auth/privacy-policy'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'

// Create Virtual Routes

const ProjectsmanagerLazyImport = createFileRoute('/projects_manager')()
const FilesmanagerLazyImport = createFileRoute('/files_manager')()
const CompanyLazyImport = createFileRoute('/company')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProjectsmanagerLazyRoute = ProjectsmanagerLazyImport.update({
  id: '/projects_manager',
  path: '/projects_manager',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects_manager.lazy').then((d) => d.Route),
)

const FilesmanagerLazyRoute = FilesmanagerLazyImport.update({
  id: '/files_manager',
  path: '/files_manager',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/files_manager.lazy').then((d) => d.Route))

const CompanyLazyRoute = CompanyLazyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/company.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const ProjectsRoute = ProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectsIdRoute = ProjectsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)

const AuthServiceTermRoute = AuthServiceTermImport.update({
  id: '/auth/service-term',
  path: '/auth/service-term',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthPrivacyPolicyRoute = AuthPrivacyPolicyImport.update({
  id: '/auth/privacy-policy',
  path: '/auth/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyLazyImport
      parentRoute: typeof rootRoute
    }
    '/files_manager': {
      id: '/files_manager'
      path: '/files_manager'
      fullPath: '/files_manager'
      preLoaderRoute: typeof FilesmanagerLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects_manager': {
      id: '/projects_manager'
      path: '/projects_manager'
      fullPath: '/projects_manager'
      preLoaderRoute: typeof ProjectsmanagerLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/privacy-policy': {
      id: '/auth/privacy-policy'
      path: '/auth/privacy-policy'
      fullPath: '/auth/privacy-policy'
      preLoaderRoute: typeof AuthPrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/service-term': {
      id: '/auth/service-term'
      path: '/auth/service-term'
      fullPath: '/auth/service-term'
      preLoaderRoute: typeof AuthServiceTermImport
      parentRoute: typeof rootRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdImport
      parentRoute: typeof ProjectsImport
    }
  }
}

// Create and export the route tree

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/company': typeof CompanyLazyRoute
  '/files_manager': typeof FilesmanagerLazyRoute
  '/projects_manager': typeof ProjectsmanagerLazyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/privacy-policy': typeof AuthPrivacyPolicyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/service-term': typeof AuthServiceTermRoute
  '/projects/$id': typeof ProjectsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/company': typeof CompanyLazyRoute
  '/files_manager': typeof FilesmanagerLazyRoute
  '/projects_manager': typeof ProjectsmanagerLazyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/privacy-policy': typeof AuthPrivacyPolicyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/service-term': typeof AuthServiceTermRoute
  '/projects/$id': typeof ProjectsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/company': typeof CompanyLazyRoute
  '/files_manager': typeof FilesmanagerLazyRoute
  '/projects_manager': typeof ProjectsmanagerLazyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/privacy-policy': typeof AuthPrivacyPolicyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/service-term': typeof AuthServiceTermRoute
  '/projects/$id': typeof ProjectsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/about'
    | '/company'
    | '/files_manager'
    | '/projects_manager'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/privacy-policy'
    | '/auth/register'
    | '/auth/service-term'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/about'
    | '/company'
    | '/files_manager'
    | '/projects_manager'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/privacy-policy'
    | '/auth/register'
    | '/auth/service-term'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/about'
    | '/company'
    | '/files_manager'
    | '/projects_manager'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/privacy-policy'
    | '/auth/register'
    | '/auth/service-term'
    | '/projects/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  CompanyLazyRoute: typeof CompanyLazyRoute
  FilesmanagerLazyRoute: typeof FilesmanagerLazyRoute
  ProjectsmanagerLazyRoute: typeof ProjectsmanagerLazyRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPrivacyPolicyRoute: typeof AuthPrivacyPolicyRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthServiceTermRoute: typeof AuthServiceTermRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  CompanyLazyRoute: CompanyLazyRoute,
  FilesmanagerLazyRoute: FilesmanagerLazyRoute,
  ProjectsmanagerLazyRoute: ProjectsmanagerLazyRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPrivacyPolicyRoute: AuthPrivacyPolicyRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthServiceTermRoute: AuthServiceTermRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects",
        "/about",
        "/company",
        "/files_manager",
        "/projects_manager",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/privacy-policy",
        "/auth/register",
        "/auth/service-term"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx",
      "children": [
        "/projects/$id"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/company": {
      "filePath": "company.lazy.tsx"
    },
    "/files_manager": {
      "filePath": "files_manager.lazy.tsx"
    },
    "/projects_manager": {
      "filePath": "projects_manager.lazy.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/privacy-policy": {
      "filePath": "auth/privacy-policy.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/service-term": {
      "filePath": "auth/service-term.tsx"
    },
    "/projects/$id": {
      "filePath": "projects.$id.tsx",
      "parent": "/projects"
    }
  }
}
ROUTE_MANIFEST_END */
