# Generated by Django 5.1.4 on 2025-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('HumanMessage', 'User'), ('AIMessage', 'Assistant'), ('SystemMessage', 'System')], max_length=20),
        ),
    ]
