"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os, sys 
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
#sys.path.insert(0,str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eue96xem5j9v0-sj$@blb(bh56es614w@_o7gmq$q15!xfnjfk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['115.159.6.83', 'localhost', '127.0.0.1','testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',  # 用于存储文件对象
    'apps.authentication',
    'apps.files',
    'apps.projects',
    'apps.doc_analysis',
    'apps.chat',
    'django_filters',  # 用于过滤
    'drf_spectacular',  # 用于生成OPENAPI文档
    'rest_framework_simplejwt.token_blacklist', # 用于管理JWT令牌的黑名单 for logout


]



# ----------------------- 腾讯COS文件存储配置 (Boto3+Storage) 暂时弃用 --------------------------------------
#DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"  # 使用Boto3+Storage (推荐)
DEFAULT_FILE_STORAGE = 'apps.files.storage.COSStorage'  # 使用COSStorage
#DEFAULT_FILE_STORAGE = 'apps.files.storage.AsyncCOSStorage'  # 使用AsyncCOSStorage
AWS_ACCESS_KEY_ID = os.getenv('TENCENT_COS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('TENCENT_COS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'bidpilot-1332405885'
AWS_S3_REGION_NAME = 'ap-shanghai'  # 例如：ap-beijing

# f"https://{COS_BUCKET_NAME}.cos.{COS_REGION}.myqcloud.com"
AWS_S3_ENDPOINT_URL = 'https://bidpilot-1332405885.cos.ap-shanghai.myqcloud.com'
AWS_S3_ADDRESSING_STYLE = 'path' # 路径风格
AWS_QUERYSTRING_AUTH = False  # 不加签名，直接公开 URL 访问
AWS_DEFAULT_ACL = 'public-read'  # 设置默认的访问控制级别为公开读取

# AWS_S3_CUSTOM_DOMAIN 主要用于生成文件的访问 URL，不影响存储路径。它决定了通过 file.url 获取到的 URL 的域名部分
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.cos.{AWS_S3_REGION_NAME}.myqcloud.com"
AWS_S3_FILE_OVERWRITE = False  # 不覆盖同名文件
AWS_LOCATION = ''  # 这会生成类似 uploads/2025/01/31/ 的路径


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 需要放在最前面
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # 数据库引擎
        'NAME': 'bidpilot_new',  # 数据库名称
        'USER': 'postgres',  # 数据库用户
        'PASSWORD': '123456',  # 数据库密码\
        'HOST': 'localhost',  # 数据库主机
        'PORT': '5432',  # 数据库端口
        'OPTIONS': {
            'client_encoding': 'UTF8',  # 确保客户端编码为 UTF-8
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'   # 语言 英文是en-us，中文是zh-hans

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 收集静态文件的目录

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------ DRF 配置 用于生成OPENAPI文档 ------------------------------
# DRF 配置
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}




# Spectacular 设置
SPECTACULAR_SETTINGS = {
    'TITLE': 'BidPilot API',
    'DESCRIPTION': 'BidPilot 后端 API 文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'auth', 'description': '认证相关接口'},
    ],
}
# ----------------------------------------------------------------------------------------------




# -----------------------  CORS设置 （与前端连接的必要配置）--------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React 开发服务器
    "http://localhost:5173",  # Vite 开发服务器
    "http://115.159.6.83:5173",  # Vite 开发服务器 
    "http://115.159.6.83:3000",  # React 开发服务器 
]

CORS_ALLOW_ALL_ORIGINS = True  # 允许所有来源 (生产环境不要开启)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

